### ISSUE TITLE
Could you please provide data in `anatomical_data` directory?

### ISSUE THREAD

**Issue by chaoming0625** [seanfw/dopamine-dist-wm#1]
Dear @seanfw , I found your work is very very excellent and has deep inspiration for me. You also kindly provide the source code of your Neuron paper. However, when I run your source code, I found there is a missing data of `anatomical_data`. Could you please provide the data in this directory. Thank you very very much!

**Comment by seanfw** [comment]
Dear @chaoming0625 - I am very sorry that I missed this comment! I have now uploaded the anatomical data. Please let me know if you have any issues, or catch any bugs.
